### ISSUE TITLE
Error when clicking previous track after 3 sec. on the mini player

### ISSUE THREAD

**Issue by mnordstrom** [ToneDen/toneden-sdk#64]
I am using the turn-key solution of the player, no dev happening here, and have noticed that with the mini player I can go forward and reverse along the playlist as long as I do so before three seconds. After that time period I can only go forward, sometimes, and not back. When I attempt to go back the console logs a series of errors. I am using two tracks in the playlist. One from a public link and one from a private share link. Any help would be appreciated. Thanks!

`iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at Ue.Object.defineProperty.get (http://sd.toneden.io/production/v2/toneden.js:41:30804)
    at http://sd.toneden.io/production/v2/toneden.js:2:1447
    at r (http://sd.toneden.io/production/v2/toneden.js:2:1283)
    at u (http://sd.toneden.io/production/v2/toneden.js:2:4956)
    at r (http://sd.toneden.io/production/v2/toneden.js:3:1790)
    at r (http://sd.toneden.io/production/v2/toneden.js:3:825)
    at r (http://sd.toneden.io/production/v2/toneden.js:3:517)
    at http://sd.toneden.io/production/v2/toneden.js:19:22320
    at Array.map (native)
    at http://sd.toneden.io/production/v2/toneden.js:19:22296
toneden.js:41 iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at Ue.Object.defineProperty.get (http://sd.toneden.io/production/v2/toneden.js:41:30804)
    at r (http://sd.toneden.io/production/v2/toneden.js:2:3323)
    at r (http://sd.toneden.io/production/v2/toneden.js:2:5035)
    at u (http://sd.toneden.io/production/v2/toneden.js:2:4961)
    at r (http://sd.toneden.io/production/v2/toneden.js:3:1790)
    at r (http://sd.toneden.io/production/v2/toneden.js:3:825)
    at r (http://sd.toneden.io/production/v2/toneden.js:3:517)
    at http://sd.toneden.io/production/v2/toneden.js:19:22320
    at Array.map (native)
    at http://sd.toneden.io/production/v2/toneden.js:19:22296
toneden.js:41 iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at Ue.Object.defineProperty.get (http://sd.toneden.io/production/v2/toneden.js:41:30804)
    at http://sd.toneden.io/production/v2/toneden.js:2:1447
    at r (http://sd.toneden.io/production/v2/toneden.js:2:1283)
    at r (http://sd.toneden.io/production/v2/toneden.js:2:1093)
    at r (http://sd.toneden.io/production/v2/toneden.js:2:3349)
    at r (http://sd.toneden.io/production/v2/toneden.js:2:5035)
    at u (http://sd.toneden.io/production/v2/toneden.js:2:4961)
    at r (http://sd.toneden.io/production/v2/toneden.js:3:1790)
    at r (http://sd.toneden.io/production/v2/toneden.js:3:825)
    at r (http://sd.toneden.io/production/v2/toneden.js:3:517)
toneden.js:41 iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at Ue.Object.defineProperty.get (http://sd.toneden.io/production/v2/toneden.js:41:30804)
    at r (http://sd.toneden.io/production/v2/toneden.js:2:5057)
    at u (http://sd.toneden.io/production/v2/toneden.js:2:4961)
    at r (http://sd.toneden.io/production/v2/toneden.js:3:1790)
    at r (http://sd.toneden.io/production/v2/toneden.js:3:825)
    at r (http://sd.toneden.io/production/v2/toneden.js:3:517)
    at http://sd.toneden.io/production/v2/toneden.js:19:22320
    at Array.map (native)
    at http://sd.toneden.io/production/v2/toneden.js:19:22296
    at http://sd.toneden.io/production/v2/toneden.js:26:203
toneden.js:41 iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at Ue.Object.defineProperty.get (http://sd.toneden.io/production/v2/toneden.js:41:30804)
    at http://sd.toneden.io/production/v2/toneden.js:2:1447
    at r (http://sd.toneden.io/production/v2/toneden.js:2:1283)
    at r (http://sd.toneden.io/production/v2/toneden.js:2:1093)
    at r (http://sd.toneden.io/production/v2/toneden.js:2:5085)
    at u (http://sd.toneden.io/production/v2/toneden.js:2:4961)
    at r (http://sd.toneden.io/production/v2/toneden.js:3:1790)
    at r (http://sd.toneden.io/production/v2/toneden.js:3:825)
    at r (http://sd.toneden.io/production/v2/toneden.js:3:517)
    at http://sd.toneden.io/production/v2/toneden.js:19:22320
toneden.js:1 player.audioInterface.track_error event dispatched with payload  Object {error: Error: I don't know how to deal with that URL.
    at p.parameters.cache.p.resolveCache.(anonymous f…, trackID: undefined}
3toneden.js:
19 Uncaught TypeError: Cannot read property 'setPosition' of undefined(anonymous function) @ toneden.js:19(anonymous function) @ toneden.js:26(anonymous function) @ toneden.js:26(anonymous function) @ toneden.js:19(anonymous function) @ toneden.js:26(anonymous function) @ toneden.js:26(anonymous function) @ toneden.js:26o.run @ toneden.js:2r @ toneden.js:2
toneden.js:1 player.audioInterface.track_ready event dispatched with payload  Object {sound: a, trackID: "track_2"}`

**Comment by elsbree** [comment]
*Note: I'm closing every issue on this repo with this message.*

I apologize for not being in contact earlier. We recently received notice from SoundCloud that they're shutting down their external streaming API for business reasons that I won't speculate about. 

**Every user of a custom SoundCloud player, ours included, will need to switch to [their embedded player](https://developers.soundcloud.com/docs/widget) in order to stream songs from SoundCloud.**

It's disappointing that we have to be the ones to break this news to developers, and I'm sorry for the inconvenience it's caused the users of our player. I'll leave this repo up and add this message to the top of the README so that others become aware of the situation.
